import = ["colors.toml"]

import = ["colors.toml"]

[window]
startup_mode = "Fullscreen"

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"

[keyboard]
bindings = [
    { mods="Control", key="V",  action="Paste" },
]

[mouse]
hide_when_typing = true
