tap "homebrew/bundle"

brew "bash"
brew "coreutils"
brew "ghostscript"  # Pdf manip
brew "mas"          # Mac App Store CLI
brew "pixi"
brew "rustup-init"

tap "tinted-theming/tinted"
brew "tinty"

brew "stats"
cask "alacritty"
cask "docker"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "gimp"
cask "google-chrome"
cask "inkscape"
cask "karabiner-elements"
cask "monitorcontrol"
cask "proton-drive"
cask "proton-mail"
cask "proton-pass"
cask "protonvpn"
cask "raycast"
cask "signal"
cask "spotify"
cask --no-quarantine "stretchly"
cask "transmission"
cask "vlc"

mas "Enchanted", id: 6474268307

# QuantStack
cask "zulip"
