tap "homebrew/bundle"

brew "bash"
brew "coreutils"
brew "ghostscript"  # Pdf manip
brew "mas"          # Mac App Store CLI
brew "pixi"
brew "rustup-init"

cask "alacritty"
cask "bitwarden"
cask "breaktimer"
cask "docker"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "gimp"
cask "google-chrome"
cask "inkscape"
cask "karabiner-elements"
cask "mattermost"
cask "megasync"
cask "monitorcontrol"
cask "proton-drive"
cask "proton-mail"
cask "protonvpn"
cask "raycast"
cask "signal"
cask "spotify"
cask "transmission"
cask "vlc"

mas "Enchanted", id: 6474268307
