default-scheme = "base16-humanoid-dark"

[[items]]
name = "shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = "source %f"

[[items]]
name = "tinted-terminal"
path = "https://github.com/tinted-theming/tinted-terminal"
themes-dir = "themes/alacritty"
supported-systems = ["base16", "base24"]
hook = "cp %f ${XDG_CONFIG_HOME}/alacritty/colors.toml"
