# Exit if non-interactive shell
[[ $- != *i* ]] && return

# Script directory requires non POSIX shell dependant function in the case the script is sourced.
DIR="$(cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")" )" && pwd)"

source "${DIR}/machines.sh"  # Need to be sourced first
source "${DIR}/general.sh"
if [ -f "${DIR}/secrets.sh" ]; then
	source "${DIR}/secrets.sh"
fi
source "${DIR}/aliases.sh"  # Need to be sourced last
