#!/usr/bin/env bash
#
set -o errexit -o pipefail -o nounset

function __main () {
    local -r org="$(dirname "${1}")"
    local -r repo="$(basename "${1}")"
    local -r dir_org="${WORKSPACE_DIR}/github.com/${org}"
    local -r dir_repo="${dir_org}/${repo}"
    if [[ ! -d "${dir_repo}" ]]; then
        mkdir -p "${dir_org}"
        cd "${dir_org}"
        if [[ "${org}" == "AntoinePrv" ]]; then
            gh repo clone "${org}/${repo}"
        else
            local -r fork_name="fork-${org}-${repo}"
            gh repo fork --fork-name "${fork_name}" --clone "${org}/${repo}"
            mv "${fork_name}" "${repo}"
            cd "${repo}"
            # Point default branch to upstream
            local -r branch="$(git rev-parse --abbrev-ref HEAD)"
            git branch "${branch}" --set-upstream-to "upstream/${branch}"
        fi
    else
        cd "${dir_repo}"
        git fetch --prune --all
    fi
}

__main "${1:-${PROJECT}}"
