# Exit if non-interactive shell
[[ $- != *i* ]] && return

# This files just source all other files in bash folder ending in .bashrc
for file in $(find -L ~/.config/bash -type f -name '*.bashrc'); do
	source "$file"
done
